### ISSUE TITLE
Joenn

### ISSUE THREAD

**Issue by Jaymarkf** [Jaymarkf/bulsueprocurement-laravel#11]
yung sa http://127.0.0.1:8000/purchase-order  na template pala pre

pagaya ng table columns at yung UI sa existing site then 
pa link ng button papunta sa "new purchase order" tapos yung template UI nya

then dun sa inspection and acceptance merong create new button pa link na din po ng url at palagyan na din ng tempalte yung loob

ganun lang muna pag tapos na po pa push na sa branch nyu  then close ko na tong issue at another ulit

**Comment by zZJoennZz** [comment]
[Done :)](https://github.com/Jaymarkf/bulsueprocurement-laravel/commit/5e3be769cec5d1be2aac12c1d63aec64e5c17150)

**Comment by Jaymarkf** [comment]
Thanks

**Comment by Jaymarkf** [comment]
close ko na po yung issue
